const { pool } = require('../config/database');
const crypto = require('crypto');

class EvacuationService {
  async getAdvisories(filters = {}) {
    let query = `SELECT * FROM evacuation_advisories`;
    let args = [];
    if (filters.status) {
      query += ` WHERE status = $1`;
      args.push(filters.status);
    }
    query += ` ORDER BY created_at DESC`;
    
    try {
      const res = await pool.query(query, args);
      return res.rows;
    } catch (e) {
      return [];
    }
  }

  async getAdvisoryById(id) {
    try {
      const res = await pool.query(`SELECT * FROM evacuation_advisories WHERE id = $1`, [id]);
      return res.rows[0];
    } catch (e) {
      return null;
    }
  }

  async generateRecommendation(scenarioData) {
    // Decision Support Engine Logic
    let recommendation = 'NO_ACTION_REQUIRED';
    let reasons = [];
    let uncertainties = [];
    
    if (scenarioData.hazard_severity === 'CRITICAL' || scenarioData.hazard_severity === 'HIGH') {
      reasons.push(`${scenarioData.hazard_severity} ${scenarioData.hazard_type} risk assessed.`);
      
      if (scenarioData.population_at_risk > 0) {
        reasons.push(`Population exposure detected (${scenarioData.population_at_risk} at risk).`);
        
        if (scenarioData.shelter_capacity_available >= scenarioData.shelter_required) {
          reasons.push(`Sufficient shelter capacity available.`);
          recommendation = 'REVIEW_FOR_EVACUATION';
        } else {
          reasons.push(`WARNING: Shelter capacity gap detected. Need ${scenarioData.shelter_required - scenarioData.shelter_capacity_available} more spaces.`);
          recommendation = 'REVIEW_FOR_EVACUATION';
        }
      }
    }

    if (scenarioData.data_age_minutes > 30) {
      uncertainties.push(`Road condition and shelter data is ${scenarioData.data_age_minutes} minutes old.`);
    }

    return {
      recommendation,
      reasons,
      uncertainties,
      source_types: scenarioData.source_types || ['AI RISK ASSESSMENT']
    };
  }

  async createAdvisory(data, userId) {
    const advisoryCode = 'EVAC-' + new Date().getFullYear() + '-' + crypto.randomBytes(3).toString('hex').toUpperCase();
    
    const query = `
      INSERT INTO evacuation_advisories (
        advisory_code, title, description, hazard_type, severity, status, source_type,
        population_at_risk, estimated_affected, shelter_required,
        created_by, reason, confidence, data_freshness
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
      RETURNING *
    `;
    const args = [
      advisoryCode, data.title, data.description, data.hazard_type, data.severity, 'PENDING_REVIEW', data.source_type,
      data.population_at_risk || 0, data.estimated_affected || 0, data.shelter_required || 0,
      userId, data.reason, data.confidence, data.data_freshness || 'FRESH'
    ];

    try {
      const res = await pool.query(query, args);
      const advisory = res.rows[0];

      await this.logTimeline(advisory.id, 'CREATED', null, 'PENDING_REVIEW', userId, 'Advisory generated by decision support engine.');
      
      return advisory;
    } catch (e) {
      console.error(e);
      throw new Error('Failed to create advisory');
    }
  }

  async logTimeline(advisoryId, actionType, oldStatus, newStatus, userId, note) {
    try {
      await pool.query(`
        INSERT INTO evacuation_timeline (advisory_id, action_type, old_status, new_status, actor_id, note)
        VALUES ($1, $2, $3, $4, $5, $6)
      `, [advisoryId, actionType, oldStatus, newStatus, userId, note]);
    } catch (e) {
      console.error("Timeline log failed", e);
    }
  }

  async updateStatus(id, newStatus, userId, note) {
    try {
      const current = await this.getAdvisoryById(id);
      if (!current) throw new Error('Not found');

      let updateQuery = `UPDATE evacuation_advisories SET status = $1, updated_at = NOW()`;
      const args = [newStatus];
      let idx = 2;

      if (newStatus === 'APPROVED') {
        updateQuery += `, approved_by = $${idx++}, approved_at = NOW()`;
        args.push(userId);
      } else if (newStatus === 'ACTIVE') {
        updateQuery += `, activated_at = NOW()`;
      } else if (newStatus === 'COMPLETED') {
        updateQuery += `, completed_at = NOW()`;
      } else if (newStatus === 'CANCELLED' || newStatus === 'REJECTED') {
        updateQuery += `, cancelled_at = NOW()`;
      }

      updateQuery += ` WHERE id = $${idx} RETURNING *`;
      args.push(id);

      const res = await pool.query(updateQuery, args);
      await this.logTimeline(id, `STATUS_${newStatus}`, current.status, newStatus, userId, note);
      
      return res.rows[0];
    } catch (e) {
      throw e;
    }
  }
}

module.exports = new EvacuationService();
