import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../../services/api';
import { toast } from 'react-hot-toast';

const EvacuationSimulator = () => {
  const navigate = useNavigate();
  const [isSimulating, setIsSimulating] = useState(false);
  const [result, setResult] = useState<any>(null);

  const handleRunSimulation = async () => {
    setIsSimulating(true);
    // Hardcoded Demo Scenario payload for Vijayawada
    const payload = {
      title: 'DEMO/SIMULATION: Vijayawada Flood Evacuation',
      description: 'Simulated evacuation advisory due to rapid rising flood waters in Zone A.',
      hazard_type: 'FLOOD',
      severity: 'CRITICAL',
      hazard_severity: 'CRITICAL',
      population_at_risk: 1200,
      shelter_required: 800,
      shelter_capacity_available: 500, // Intentional gap to trigger warning
      data_age_minutes: 5,
      source_type: 'DEMO/SIMULATION',
      reason: 'Generated by authority simulation.',
      confidence: 0.85
    };

    try {
      // 1. Generate Recommendation
      const recRes = await api.post('/evacuation/simulation', payload);
      const rec = recRes.data.data;
      
      // Merge simulation result with payload
      payload.reason = rec.reasons.join('\n');
      
      // 2. Create the actual advisory in DB as PENDING_REVIEW
      const advRes = await api.post('/evacuation', payload);
      
      setResult(advRes.data.data);
      toast.success("Simulation Complete. Advisory created in PENDING_REVIEW state.");
    } catch (err) {
      toast.error('Simulation failed.');
    } finally {
      setIsSimulating(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <button onClick={() => navigate(-1)} className="text-gray-400 hover:text-white text-sm flex items-center mb-4">
        &larr; Back to Dashboard
      </button>

      <div className="bg-darkslate border border-warning rounded-xl p-8 shadow-2xl">
        <header className="mb-6 text-center">
          <span className="bg-warning text-darkslate font-bold px-3 py-1 rounded uppercase text-sm mb-4 inline-block">Demo Mode / Simulator</span>
          <h1 className="text-3xl font-bold text-white mb-2">Vijayawada Flood Evacuation Simulation</h1>
          <p className="text-gray-400">Run a complete end-to-end simulation of the Decision Support System.</p>
        </header>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          <div className="bg-charcoal border border-gray-700 p-4 rounded text-sm text-gray-300">
            <h3 className="font-bold text-white mb-2 border-b border-gray-600 pb-2">Scenario Parameters</h3>
            <ul className="space-y-2">
              <li><strong>Hazard:</strong> Heavy Rainfall &rarr; River Flood</li>
              <li><strong>Affected Zone:</strong> Vijayawada Lowlands</li>
              <li><strong>Population Exposed:</strong> ~1,200</li>
              <li><strong>Shelter Capacity:</strong> 500 spaces available</li>
              <li><strong>Expected Gap:</strong> 300 spaces short</li>
            </ul>
          </div>
          
          <div className="bg-charcoal border border-gray-700 p-4 rounded text-sm text-gray-300">
            <h3 className="font-bold text-white mb-2 border-b border-gray-600 pb-2">Expected Outcomes</h3>
            <ul className="space-y-2 list-disc list-inside">
              <li>AI generates recommendation</li>
              <li>Identifies capacity bottleneck</li>
              <li>Calculates lower-risk routes</li>
              <li>Pushes advisory to PENDING_REVIEW queue</li>
            </ul>
          </div>
        </div>

        <div className="text-center">
          <button 
            onClick={handleRunSimulation} 
            disabled={isSimulating}
            className="bg-info hover:bg-blue-400 text-darkslate font-bold py-3 px-8 rounded-lg shadow-lg transition-colors disabled:opacity-50"
          >
            {isSimulating ? 'Running Simulation...' : 'Execute Simulation Scenario'}
          </button>
        </div>

        {result && (
          <div className="mt-8 p-6 bg-success/10 border border-success rounded-lg text-center">
            <h3 className="text-success font-bold text-xl mb-2">Simulation Successful</h3>
            <p className="text-gray-300 mb-4">Advisory <span className="font-mono text-white">{result.advisory_code}</span> generated.</p>
            <button onClick={() => navigate(`/authority/evacuation/${result.id}`)} className="bg-success text-darkslate px-6 py-2 rounded font-bold hover:bg-green-500 transition">
              Proceed to Authority Review Workflow
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default EvacuationSimulator;
